name: "Setup Just and UV"
description: "Setup just and uv without installing dependencies"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@v3

    - name: Setup uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
