name: "Setup Just and UV"
description: "Setup just and uv without installing dependencies"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

    - name: Setup uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      with:
        enable-cache: true
        version: "0.12.0"
