name: "Setup Just and UV"
description: "Setup just and uv without installing dependencies"
runs:
  using: "composite"
  steps:
    - name: Install just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4

    - name: Setup uv
      uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
      with:
        enable-cache: true
        version: "0.12.0"
