name: "Install Python depedencies"
description: "Install Python dependencies using uv and just"
runs:
  using: "composite"
  steps:
    - name: Set up Python 3.14
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: "3.14"

    - name: Setup tools
      uses: ./.github/actions/setup_just_and_uv

    - name: Install dependencies
      run: just install
      shell: bash
